name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        uses: brewing-dev/hf-spaces-sync@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          huggingface_token: ${{ secrets.HF_TOKEN }}
          huggingface_repo: jessecodesometimes/Spoke
          huggingface_branch: main
